defmodule OpenSauce.Test.AuthHelpers do
  @moduledoc """
  Test-only helpers for creating users and signing in connections.

  The dirt auth model: User (email-only, magic-link) → OrganisationMember (role + org_id).
  `current_user` on the socket is a User; `current_member` is an OrganisationMember.
  """

  alias OpenSauce.Accounts.{Organisation, OrganisationMember, User}

  @doc """
  Creates a User, Organisation, and OrganisationMember for the given role.
  Returns `{user_with_token, member}`.

  The `role` option maps to OrganisationMember roles: `:staff`, `:manager`, `:owner`.
  `:admin` is accepted as an alias for `:owner` for test convenience.
  """
  def register_user!(opts \\ []) do
    raw_role = Keyword.get(opts, :role, :staff)
    member_role = if raw_role == :admin, do: :owner, else: raw_role
    email = unique_email(raw_role)

    user =
      User
      |> Ash.Changeset.for_create(:create, %{email: email})
      |> Ash.create!(authorize?: false)

    {:ok, token, _claims} = AshAuthentication.Jwt.token_for_user(user)
    user = Ash.Resource.put_metadata(user, :token, token)

    n = System.unique_integer([:positive])

    org =
      Organisation
      |> Ash.Changeset.for_create(:create, %{name: "Test Org #{n}", slug: "test-org-#{n}"})
      |> Ash.create!(authorize?: false)

    member =
      OrganisationMember
      |> Ash.Changeset.for_create(:create, %{
        role: member_role,
        user_id: user.id,
        organisation_id: org.id
      })
      |> Ash.create!(authorize?: false)

    user = Ash.Resource.put_metadata(user, :organisation_id, org.id)

    {user, member}
  end

  @doc """
  No-op — token is already generated by `register_user!/1`.
  Kept for call-site compatibility.
  """
  def ensure_token!({user, member}), do: {user, member}
  def ensure_token!(%{__metadata__: %{token: token}} = user) when is_binary(token), do: user
  def ensure_token!(user), do: user

  @doc """
  Signs in the given user on the provided connection by storing the token in session,
  assigning `:current_user`, and setting the `organisation_id` session key.
  """
  def sign_in(conn, user) do
    org_id = user.__metadata__[:organisation_id]

    conn
    |> Plug.Test.put_req_cookie("timezone", "Etc/UTC")
    |> AshAuthentication.Phoenix.Plug.store_in_session(user)
    |> Plug.Conn.assign(:current_user, user)
    |> Plug.Conn.put_session(:organisation_id, org_id)
  end

  defp unique_email(role), do: "#{role}+#{System.unique_integer([:positive])}@local"
end
