import Config

config :opensauce, OpenSauce.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  # Binding to loopback ipv4 address prevents access from other machines.
  # Watch static and templates for browser reloading.
  password: "postgres",
  hostname: "localhost",
  database: "opensauce_dirt_dev",
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :opensauce, OpenSauce.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: Base.decode64!("dVBPc3k5cExja3A2aGR6bmFiY2RlZjAxMjM0NTY3ODk=")}
  ]

config :opensauce, OpenSauceWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  # ## SSL Support
  #
  # In order to use HTTPS in development, a self-signed
  # certificate can be generated by running the following
  # Mix task:
  #
  # Enable dev routes for dashboard and mailbox

  #     mix phx.gen.cert
  #

  #
  # The `http:` config above can be replaced with:

  # Run `mix help phx.gen.cert` for more information.
  #
  #     https: [
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NlbIq9/9aO9+5xxg8ESxxFI7ay172FlEI5IVJvhLx50ZcZbWLjV1L1ito7aZ0fiM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:opensauce, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:opensauce, ~w(--watch)]}
  ]

config :opensauce, OpenSauceWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/opensauce_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"storybook/.*(exs)$"
    ]

    #       certfile: "priv/cert/selfsigned.pem"

    # Do not include metadata nor timestamps in development logs
    # in production as building large stacktraces may be expensive.
    # Include HEEx debug annotations as HTML comments in rendered markup
    #       cipher_suite: :strong,
    #       keyfile: "priv/cert/selfsigned_key.pem",
  ]

#       port: 4001,
# Configure your database
#     ],
# configured to run both http and https servers on
#
# different ports.
config :opensauce, dev_routes: true, token_signing_secret: "1Y4H7uJJNzu5KtTktCIrtiyGZ+A0eBS9"

config :logger, :console, format: "[$level] $message\n"

config :phoenix, :plug_init_mode, :runtime
# If desired, both `http:` and `https:` keys can be
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :swoosh, :api_client, false

config :opensauce,
  storage_adapter: OpenSauce.Storage.Local,
  upload_dir: Path.join([File.cwd!(), "priv", "static", "uploads"])

# Set a higher stacktrace during development. Avoid configuring such
# Disable swoosh api client as it is only required for production adapters.
# Initialize plugs at runtime for faster development compilation
