defmodule OpenSauce.Repo.Migrations.AddMemberStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisation_members) do
      add :status, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:accounts_organisation_members) do
      remove :status
    end
  end
end
