defmodule OpenSauce.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false, default: "client_work"
      add :service_category, :text
      add :account_code, :text
      add :scheduled_for, :date
      add :status, :text, null: false, default: "scheduled"
      add :duration_estimate, :bigint
      add :realized_cost, :decimal
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :garden_id, :uuid
      add :engagement_id, :uuid
      add :invoice_id, :uuid
      add :containing_shift_id, :uuid
      add :actor_id, :uuid
    end

    create index(:orders_jobs, [:organisation_id, :garden_id], name: "orders_jobs_garden_id_index")

    create index(:orders_jobs, [:organisation_id, :engagement_id], name: "orders_jobs_engagement_id_index")

    create index(:orders_jobs, [:organisation_id, :containing_shift_id], name: "orders_jobs_containing_shift_id_index")

    create index(:orders_jobs, [:organisation_id, :status], name: "orders_jobs_status_index")

    create index(:orders_jobs, [:organisation_id, :scheduled_for], name: "orders_jobs_scheduled_for_index")

    create table(:orders_job_staff, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :job_id, :uuid, null: false
      add :member_id, :uuid, null: false
    end

    create index(:orders_job_staff, [:organisation_id, :job_id], name: "orders_job_staff_job_id_index")

    create unique_index(:orders_job_staff, [:organisation_id, :job_id, :member_id],
             name: "orders_job_staff_unique_staff_assignment_index"
           )

    create table(:orders_job_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :job_id, :uuid, null: false
      add :supplier_catalog_item_id, :uuid, null: false
    end

    create table(:orders_job_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :data, :map, null: false
      add :actor_id, :uuid
      add :timestamp, :utc_datetime, null: false
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :job_id, :uuid, null: false
    end

    create index(:orders_job_events, [:organisation_id, :job_id, :timestamp],
             name: "orders_job_events_job_timeline_index"
           )

    create table(:orders_job_event_staff, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :man_hour_rate, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :job_event_id, :uuid, null: false
      add :member_id, :uuid, null: false
    end

    create index(:orders_job_event_staff, [:organisation_id, :job_event_id],
             name: "orders_job_event_staff_job_event_id_index"
           )

    create table(:orders_job_event_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :job_event_id, :uuid, null: false
      add :material_id, :uuid, null: false
    end

    create table(:operations_venues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create table(:operations_storage_locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :venue_id, :uuid, null: false
    end

    create table(:inventory_suppliers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :contact_name, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create table(:inventory_supplier_catalogs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :season, :text, null: false, default: "year_round"
      add :year, :bigint, null: false
      add :valid_from, :date
      add :valid_until, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :supplier_id, :uuid, null: false
    end

    create table(:inventory_supplier_catalog_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sku, :text, null: false
      add :name, :text, null: false
      add :latin_name, :text
      add :cultivar, :text
      add :category, :text, null: false
      add :format_description, :text
      add :size_cm, :decimal
      add :unit_price, :decimal
      add :currency, :text, default: "CAD"
      add :min_order_qty, :bigint, null: false, default: 1
      add :lead_time_days, :bigint
      add :available, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :supplier_catalog_id, :uuid, null: false
      add :material_id, :uuid
    end

    create index(:inventory_supplier_catalog_items, [:organisation_id, :supplier_catalog_id],
             name: "inventory_sci_catalog_index"
           )

    create table(:inventory_purchase_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :ordered_at, :utc_datetime
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :supplier_id, :uuid
    end

    create unique_index(:inventory_purchase_orders, [:organisation_id, :reference],
             name: "inventory_purchase_orders_reference_index"
           )

    create table(:inventory_purchase_order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :supplier_sku, :text, null: false
      add :quantity, :decimal, null: false, default: "1"
      add :confirmed_qty, :decimal
      add :received_qty, :decimal
      add :unit_price, :decimal
      add :is_reservation, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :purchase_order_id,
          references(:inventory_purchase_orders,
            column: :id,
            name: "inventory_purchase_order_items_purchase_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :supplier_catalog_item_id,
          references(:inventory_supplier_catalog_items,
            column: :id,
            name: "inventory_purchase_order_items_supplier_catalog_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :material_id, :uuid
      add :job_id, :uuid
    end

    create table(:inventory_movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :reason, :text
      add :occurred_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :lot_id, :uuid
    end

    create table(:inventory_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_purchase_order_items) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_purchase_order_items_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "inventory_purchase_order_items_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_materials) do
      add :name, :text, null: false
      add :sku, :text, null: false
      add :unit, :text, null: false
      add :price, :decimal, null: false
      add :material_type, :text, null: false, default: "supply"
      add :minimum_stock, :decimal
      add :maximum_stock, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create unique_index(:inventory_materials, [:organisation_id, :name], name: "inventory_materials_name_index")

    create unique_index(:inventory_materials, [:organisation_id, :sku], name: "inventory_materials_sku_index")

    create table(:inventory_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :venue_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :supplier_id, :uuid
    end

    create index(:inventory_lots, [:organisation_id, :supplier_id], name: "inventory_lots_supplier_id_index")

    create index(:inventory_lots, [:organisation_id, :material_id], name: "inventory_lots_material_id_index")

    create index(:inventory_lots, [:organisation_id, :lot_code],
             name: "inventory_lots_lot_code_index",
             unique: true
           )

    create table(:crm_invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :issued_on, :date, null: false, default: fragment("CURRENT_DATE")
      add :due_on, :date
      add :amount, :decimal, null: false
      add :status, :text, null: false, default: "draft"
      add :notes, :text
      add :line_items, {:array, :map}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :customer_id, :uuid, null: false
      add :engagement_id, :uuid
    end

    create index(:crm_invoices, [:organisation_id, :status], name: "crm_invoices_status_index")

    create index(:crm_invoices, [:organisation_id, :engagement_id], name: "crm_invoices_engagement_id_index")

    create index(:crm_invoices, [:organisation_id, :customer_id], name: "crm_invoices_customer_id_index")

    create table(:crm_engagements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope_description, :text
      add :install_price, :decimal
      add :maintenance_price_annual, :decimal
      add :term_start, :date
      add :term_end, :date
      add :status, :text, null: false, default: "draft"
      add :signature, :map
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :garden_id, :uuid
      add :customer_id, :uuid, null: false
    end

    create index(:crm_engagements, [:organisation_id, :status])

    create index(:crm_engagements, [:organisation_id, :garden_id])

    create index(:crm_engagements, [:organisation_id, :customer_id])

    create table(:crm_engagement_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :scheduled_date, :date
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :engagement_id, :uuid, null: false
      add :supplier_catalog_item_id, :uuid, null: false
    end

    create table(:crm_engagement_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :captured_on, :date, null: false
      add :storage_key, :text, null: false
      add :content_type, :text, null: false
      add :original_filename, :text, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :engagement_id, :uuid, null: false
    end

    create index(:crm_engagement_images, [:organisation_id, :engagement_id, :type],
             name: "crm_engagement_images_engagement_type_index"
           )

    create index(:crm_engagement_images, [:organisation_id, :engagement_id],
             name: "crm_engagement_images_engagement_id_index"
           )

    create table(:crm_customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :type, :text, null: false
      add :company_name_nickname, :text
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :text
      add :phone, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create unique_index(:crm_customers, [:organisation_id, :email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:organisation_id, :phone], name: "crm_customers_phone_index")

    create unique_index(:crm_customers, [:organisation_id, :reference], name: "crm_customers_reference_index")

    create table(:crm_addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :is_billing, :boolean, null: false, default: false
      add :is_garden, :boolean, null: false, default: false
      add :is_indoor, :boolean, null: false, default: false
      add :street, :text
      add :city, :text
      add :province, :text
      add :zip, :text
      add :country, :text
      add :location, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:crm_customers,
            column: :id,
            name: "crm_addresses_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :organisation_id, :uuid
      add :supplier_id, :uuid
    end

    create table(:accounts_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    create table(:accounts_tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:accounts_tax_rates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :rate, :decimal, null: false, default: "0"
      add :is_compound, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create table(:accounts_organisations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_jobs) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_jobs_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :garden_id,
             references(:crm_addresses,
               column: :id,
               name: "orders_jobs_garden_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :engagement_id,
             references(:crm_engagements,
               column: :id,
               name: "orders_jobs_engagement_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invoice_id,
             references(:crm_invoices,
               column: :id,
               name: "orders_jobs_invoice_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :containing_shift_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_jobs_containing_shift_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :actor_id,
             references(:accounts_users,
               column: :id,
               name: "orders_jobs_actor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_staff) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_job_staff_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_job_staff_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_materials) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_job_materials_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_job_materials_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_catalog_item_id,
             references(:inventory_supplier_catalog_items,
               column: :id,
               name: "orders_job_materials_supplier_catalog_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_events) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_job_events_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_job_events_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_event_staff) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_job_event_staff_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_event_id,
             references(:orders_job_events,
               column: :id,
               name: "orders_job_event_staff_job_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_event_materials) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_job_event_materials_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :job_event_id,
             references(:orders_job_events,
               column: :id,
               name: "orders_job_event_materials_job_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "orders_job_event_materials_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations_venues) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "operations_venues_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations_storage_locations) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "operations_storage_locations_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:operations_venues,
               column: :id,
               name: "operations_storage_locations_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_suppliers) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_suppliers_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_supplier_catalogs) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_supplier_catalogs_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_supplier_catalogs_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_supplier_catalog_items) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_supplier_catalog_items_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_catalog_id,
             references(:inventory_supplier_catalogs,
               column: :id,
               name: "inventory_supplier_catalog_items_supplier_catalog_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_supplier_catalog_items_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_purchase_orders) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_purchase_orders_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_purchase_orders_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_movements) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_movements_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_movements_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "inventory_movements_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_materials) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_materials_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_lots) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_lots_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:operations_venues,
               column: :id,
               name: "inventory_lots_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_lots_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_lots_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_invoices) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_invoices_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "crm_invoices_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :engagement_id,
             references(:crm_engagements,
               column: :id,
               name: "crm_invoices_engagement_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_engagements) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_engagements_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :garden_id,
             references(:crm_addresses,
               column: :id,
               name: "crm_engagements_garden_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "crm_engagements_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_engagement_materials) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_engagement_materials_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :engagement_id,
             references(:crm_engagements,
               column: :id,
               name: "crm_engagement_materials_engagement_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_catalog_item_id,
             references(:inventory_supplier_catalog_items,
               column: :id,
               name: "crm_engagement_materials_supplier_catalog_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_engagement_images) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_engagement_images_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :engagement_id,
             references(:crm_engagements,
               column: :id,
               name: "crm_engagement_images_engagement_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_customers) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_customers_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_addresses) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_addresses_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "crm_addresses_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_tax_rates) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "accounts_tax_rates_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_organisations) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :currency, :text, null: false, default: "CAD"
      add :tax_mode, :text, null: false, default: "exclusive"
      add :labor_overhead_percent, :decimal, null: false, default: "0"
      add :mileage_cost_per_km, :decimal, null: false, default: "0"
      add :email_from_name, :text, default: "OpenSauce"
      add :email_from_address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :head_office_venue_id,
          references(:operations_venues,
            column: :id,
            name: "accounts_organisations_head_office_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:accounts_organisations, [:slug], name: "accounts_organisations_unique_slug_index")

    create table(:accounts_organisation_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_job_staff) do
      modify :member_id,
             references(:accounts_organisation_members,
               column: :id,
               name: "orders_job_staff_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_event_staff) do
      modify :member_id,
             references(:accounts_organisation_members,
               column: :id,
               name: "orders_job_event_staff_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_organisation_members) do
      add :role, :text, null: false, default: "staff"
      add :display_title, :text
      add :labor_hourly_rate, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_organisation_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "accounts_organisation_members_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_organisation_members, [:user_id, :organisation_id],
             name: "accounts_organisation_members_unique_membership_index"
           )

    create table(:accounts_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, :map, null: false, default: %{}
      add :last_used_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "accounts_api_keys_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_api_keys, [:organisation_id, :key_hash], name: "accounts_api_keys_key_hash_index")
  end

  def down do
    drop constraint(:accounts_api_keys, "accounts_api_keys_organisation_id_fkey")

    drop_if_exists unique_index(:accounts_api_keys, [:organisation_id, :key_hash],
                     name: "accounts_api_keys_key_hash_index"
                   )

    drop table(:accounts_api_keys)

    drop constraint(:accounts_organisation_members, "accounts_organisation_members_user_id_fkey")

    drop constraint(
           :accounts_organisation_members,
           "accounts_organisation_members_organisation_id_fkey"
         )

    drop_if_exists unique_index(:accounts_organisation_members, [:user_id, :organisation_id],
                     name: "accounts_organisation_members_unique_membership_index"
                   )

    alter table(:accounts_organisation_members) do
      remove :organisation_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :labor_hourly_rate
      remove :display_title
      remove :role
    end

    drop constraint(:orders_job_event_staff, "orders_job_event_staff_member_id_fkey")

    alter table(:orders_job_event_staff) do
      modify :member_id, :uuid
    end

    drop constraint(:orders_job_staff, "orders_job_staff_member_id_fkey")

    alter table(:orders_job_staff) do
      modify :member_id, :uuid
    end

    drop table(:accounts_organisation_members)

    drop constraint(:accounts_organisations, "accounts_organisations_head_office_venue_id_fkey")

    drop_if_exists unique_index(:accounts_organisations, [:slug], name: "accounts_organisations_unique_slug_index")

    alter table(:accounts_organisations) do
      remove :head_office_venue_id
      remove :updated_at
      remove :inserted_at
      remove :email_from_address
      remove :email_from_name
      remove :mileage_cost_per_km
      remove :labor_overhead_percent
      remove :tax_mode
      remove :currency
      remove :slug
      remove :name
    end

    drop constraint(:accounts_tax_rates, "accounts_tax_rates_organisation_id_fkey")

    alter table(:accounts_tax_rates) do
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_addresses, "crm_addresses_organisation_id_fkey")

    drop constraint(:crm_addresses, "crm_addresses_supplier_id_fkey")

    alter table(:crm_addresses) do
      modify :supplier_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_customers, "crm_customers_organisation_id_fkey")

    alter table(:crm_customers) do
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_engagement_images, "crm_engagement_images_organisation_id_fkey")

    drop constraint(:crm_engagement_images, "crm_engagement_images_engagement_id_fkey")

    alter table(:crm_engagement_images) do
      modify :engagement_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_engagement_materials, "crm_engagement_materials_organisation_id_fkey")

    drop constraint(:crm_engagement_materials, "crm_engagement_materials_engagement_id_fkey")

    drop constraint(
           :crm_engagement_materials,
           "crm_engagement_materials_supplier_catalog_item_id_fkey"
         )

    alter table(:crm_engagement_materials) do
      modify :supplier_catalog_item_id, :uuid
      modify :engagement_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_engagements, "crm_engagements_organisation_id_fkey")

    drop constraint(:crm_engagements, "crm_engagements_garden_id_fkey")

    drop constraint(:crm_engagements, "crm_engagements_customer_id_fkey")

    alter table(:crm_engagements) do
      modify :customer_id, :uuid
      modify :garden_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_invoices, "crm_invoices_organisation_id_fkey")

    drop constraint(:crm_invoices, "crm_invoices_customer_id_fkey")

    drop constraint(:crm_invoices, "crm_invoices_engagement_id_fkey")

    alter table(:crm_invoices) do
      modify :engagement_id, :uuid
      modify :customer_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_lots, "inventory_lots_organisation_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_venue_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_material_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_supplier_id_fkey")

    alter table(:inventory_lots) do
      modify :supplier_id, :uuid
      modify :material_id, :uuid
      modify :venue_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_materials, "inventory_materials_organisation_id_fkey")

    alter table(:inventory_materials) do
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_movements, "inventory_movements_organisation_id_fkey")

    drop constraint(:inventory_movements, "inventory_movements_material_id_fkey")

    drop constraint(:inventory_movements, "inventory_movements_lot_id_fkey")

    alter table(:inventory_movements) do
      modify :lot_id, :uuid
      modify :material_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_organisation_id_fkey")

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_supplier_id_fkey")

    alter table(:inventory_purchase_orders) do
      modify :supplier_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(
           :inventory_supplier_catalog_items,
           "inventory_supplier_catalog_items_organisation_id_fkey"
         )

    drop constraint(
           :inventory_supplier_catalog_items,
           "inventory_supplier_catalog_items_supplier_catalog_id_fkey"
         )

    drop constraint(
           :inventory_supplier_catalog_items,
           "inventory_supplier_catalog_items_material_id_fkey"
         )

    alter table(:inventory_supplier_catalog_items) do
      modify :material_id, :uuid
      modify :supplier_catalog_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(
           :inventory_supplier_catalogs,
           "inventory_supplier_catalogs_organisation_id_fkey"
         )

    drop constraint(:inventory_supplier_catalogs, "inventory_supplier_catalogs_supplier_id_fkey")

    alter table(:inventory_supplier_catalogs) do
      modify :supplier_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_suppliers, "inventory_suppliers_organisation_id_fkey")

    alter table(:inventory_suppliers) do
      modify :organisation_id, :uuid
    end

    drop constraint(
           :operations_storage_locations,
           "operations_storage_locations_organisation_id_fkey"
         )

    drop constraint(:operations_storage_locations, "operations_storage_locations_venue_id_fkey")

    alter table(:operations_storage_locations) do
      modify :venue_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:operations_venues, "operations_venues_organisation_id_fkey")

    alter table(:operations_venues) do
      modify :organisation_id, :uuid
    end

    drop constraint(
           :orders_job_event_materials,
           "orders_job_event_materials_organisation_id_fkey"
         )

    drop constraint(:orders_job_event_materials, "orders_job_event_materials_job_event_id_fkey")

    drop constraint(:orders_job_event_materials, "orders_job_event_materials_material_id_fkey")

    alter table(:orders_job_event_materials) do
      modify :material_id, :uuid
      modify :job_event_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_job_event_staff, "orders_job_event_staff_organisation_id_fkey")

    drop constraint(:orders_job_event_staff, "orders_job_event_staff_job_event_id_fkey")

    alter table(:orders_job_event_staff) do
      modify :job_event_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_job_events, "orders_job_events_organisation_id_fkey")

    drop constraint(:orders_job_events, "orders_job_events_job_id_fkey")

    alter table(:orders_job_events) do
      modify :job_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_job_materials, "orders_job_materials_organisation_id_fkey")

    drop constraint(:orders_job_materials, "orders_job_materials_job_id_fkey")

    drop constraint(:orders_job_materials, "orders_job_materials_supplier_catalog_item_id_fkey")

    alter table(:orders_job_materials) do
      modify :supplier_catalog_item_id, :uuid
      modify :job_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_job_staff, "orders_job_staff_organisation_id_fkey")

    drop constraint(:orders_job_staff, "orders_job_staff_job_id_fkey")

    alter table(:orders_job_staff) do
      modify :job_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_jobs, "orders_jobs_organisation_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_garden_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_engagement_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_invoice_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_containing_shift_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_actor_id_fkey")

    alter table(:orders_jobs) do
      modify :actor_id, :uuid
      modify :containing_shift_id, :uuid
      modify :invoice_id, :uuid
      modify :engagement_id, :uuid
      modify :garden_id, :uuid
      modify :organisation_id, :uuid
    end

    drop table(:accounts_organisations)

    drop table(:accounts_tax_rates)

    drop table(:accounts_tokens)

    drop_if_exists unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    drop table(:accounts_users)

    drop constraint(:crm_addresses, "crm_addresses_customer_id_fkey")

    drop table(:crm_addresses)

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :reference], name: "crm_customers_reference_index")

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :phone], name: "crm_customers_phone_index")

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :email], name: "crm_customers_email_index")

    drop table(:crm_customers)

    drop_if_exists index(:crm_engagement_images, [:organisation_id, :engagement_id],
                     name: "crm_engagement_images_engagement_id_index"
                   )

    drop_if_exists index(:crm_engagement_images, [:organisation_id, :engagement_id, :type],
                     name: "crm_engagement_images_engagement_type_index"
                   )

    drop table(:crm_engagement_images)

    drop table(:crm_engagement_materials)

    drop_if_exists index(:crm_engagements, [:organisation_id, :customer_id])

    drop_if_exists index(:crm_engagements, [:organisation_id, :garden_id])

    drop_if_exists index(:crm_engagements, [:organisation_id, :status])

    drop table(:crm_engagements)

    drop_if_exists index(:crm_invoices, [:organisation_id, :customer_id], name: "crm_invoices_customer_id_index")

    drop_if_exists index(:crm_invoices, [:organisation_id, :engagement_id], name: "crm_invoices_engagement_id_index")

    drop_if_exists index(:crm_invoices, [:organisation_id, :status], name: "crm_invoices_status_index")

    drop table(:crm_invoices)

    drop_if_exists index(:inventory_lots, [:organisation_id, :lot_code], name: "inventory_lots_lot_code_index")

    drop_if_exists index(:inventory_lots, [:organisation_id, :material_id], name: "inventory_lots_material_id_index")

    drop_if_exists index(:inventory_lots, [:organisation_id, :supplier_id], name: "inventory_lots_supplier_id_index")

    drop table(:inventory_lots)

    drop_if_exists unique_index(:inventory_materials, [:organisation_id, :sku], name: "inventory_materials_sku_index")

    drop_if_exists unique_index(:inventory_materials, [:organisation_id, :name], name: "inventory_materials_name_index")

    alter table(:inventory_materials) do
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :maximum_stock
      remove :minimum_stock
      remove :material_type
      remove :price
      remove :unit
      remove :sku
      remove :name
    end

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_material_id_fkey"
         )

    drop constraint(:inventory_purchase_order_items, "inventory_purchase_order_items_job_id_fkey")

    alter table(:inventory_purchase_order_items) do
      modify :job_id, :uuid
      modify :material_id, :uuid
    end

    drop table(:inventory_materials)

    drop table(:inventory_movements)

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_purchase_order_id_fkey"
         )

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_supplier_catalog_item_id_fkey"
         )

    drop table(:inventory_purchase_order_items)

    drop_if_exists unique_index(:inventory_purchase_orders, [:organisation_id, :reference],
                     name: "inventory_purchase_orders_reference_index"
                   )

    drop table(:inventory_purchase_orders)

    drop_if_exists index(
                     :inventory_supplier_catalog_items,
                     [:organisation_id, :supplier_catalog_id],
                     name: "inventory_sci_catalog_index"
                   )

    drop table(:inventory_supplier_catalog_items)

    drop table(:inventory_supplier_catalogs)

    drop table(:inventory_suppliers)

    drop table(:operations_storage_locations)

    drop table(:operations_venues)

    drop table(:orders_job_event_materials)

    drop_if_exists index(:orders_job_event_staff, [:organisation_id, :job_event_id],
                     name: "orders_job_event_staff_job_event_id_index"
                   )

    drop table(:orders_job_event_staff)

    drop_if_exists index(:orders_job_events, [:organisation_id, :job_id, :timestamp],
                     name: "orders_job_events_job_timeline_index"
                   )

    drop table(:orders_job_events)

    drop table(:orders_job_materials)

    drop_if_exists unique_index(:orders_job_staff, [:organisation_id, :job_id, :member_id],
                     name: "orders_job_staff_unique_staff_assignment_index"
                   )

    drop_if_exists index(:orders_job_staff, [:organisation_id, :job_id], name: "orders_job_staff_job_id_index")

    drop table(:orders_job_staff)

    drop_if_exists index(:orders_jobs, [:organisation_id, :scheduled_for], name: "orders_jobs_scheduled_for_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :status], name: "orders_jobs_status_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :containing_shift_id],
                     name: "orders_jobs_containing_shift_id_index"
                   )

    drop_if_exists index(:orders_jobs, [:organisation_id, :engagement_id], name: "orders_jobs_engagement_id_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :garden_id], name: "orders_jobs_garden_id_index")

    drop table(:orders_jobs)
  end
end
