defmodule OpenSauce.Repo.Migrations.AddInvoiceSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_invoices) do
      add :snapshot, :map
    end
  end

  def down do
    alter table(:crm_invoices) do
      remove :snapshot
    end
  end
end
