defmodule OpenSauce.Repo.Migrations.AddOrganisationBrandTheme do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :brand_theme, :map
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :brand_theme
    end
  end
end
