defmodule OpenSauce.Repo.Migrations.AddOrgLogos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :logo_colour_key, :text
      add :logo_greyscale_key, :text
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :logo_greyscale_key
      remove :logo_colour_key
    end
  end
end
