defmodule OpenSauce.Repo.Migrations.RemoveFulfillmentSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      remove :shipping_flat
      remove :daily_capacity
      remove :lead_time_days
      remove :offers_delivery
      remove :offers_pickup
    end
  end

  def down do
    alter table(:settings) do
      add :offers_pickup, :boolean, null: false, default: true
      add :offers_delivery, :boolean, null: false, default: true
      add :lead_time_days, :bigint, null: false, default: 0
      add :daily_capacity, :bigint, null: false, default: 0
      add :shipping_flat, :decimal, null: false, default: "0"
    end
  end
end
