defmodule OpenSauce.Repo.Migrations.EstimateSignOffItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :estimate_sign_off_items, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :estimate_sign_off_items
    end
  end
end
