defmodule OpenSauce.Repo.Migrations.AddEngagementImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:crm_engagement_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :captured_on, :date, null: false
      add :storage_key, :text, null: false
      add :content_type, :text, null: false
      add :original_filename, :text, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "crm_engagement_images_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :engagement_id,
          references(:crm_engagements,
            column: :id,
            name: "crm_engagement_images_engagement_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:crm_engagement_images, [:organisation_id, :engagement_id, :type],
             name: "crm_engagement_images_engagement_type_index"
           )

    create index(:crm_engagement_images, [:organisation_id, :engagement_id],
             name: "crm_engagement_images_engagement_id_index"
           )
  end

  def down do
    drop constraint(:crm_engagement_images, "crm_engagement_images_organisation_id_fkey")

    drop constraint(:crm_engagement_images, "crm_engagement_images_engagement_id_fkey")

    drop_if_exists index(:crm_engagement_images, [:organisation_id, :engagement_id],
                     name: "crm_engagement_images_engagement_id_index"
                   )

    drop_if_exists index(:crm_engagement_images, [:organisation_id, :engagement_id, :type],
                     name: "crm_engagement_images_engagement_type_index"
                   )

    drop table(:crm_engagement_images)
  end
end
