defmodule OpenSauce.Repo.Migrations.AddCompoundTaxRates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings_tax_rates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :rate, :decimal, null: false, default: "0"
      add :is_compound, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "settings_tax_rates_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:accounts_organisations) do
      remove :tax_rate
    end
  end

  def down do
    alter table(:accounts_organisations) do
      add :tax_rate, :decimal, null: false, default: "0"
    end

    drop constraint(:settings_tax_rates, "settings_tax_rates_organisation_id_fkey")

    drop table(:settings_tax_rates)
  end
end
