defmodule OpenSauce.Repo.Migrations.AddJobStaffingAndCosting do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_jobs) do
      modify :status, :text, default: "scheduled"
      add :duration_estimate, :bigint
      add :realized_cost, :decimal
    end

    create table(:orders_job_staff, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_job_staff_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_id,
          references(:orders_jobs,
            column: :id,
            name: "orders_job_staff_job_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :member_id,
          references(:accounts_organisation_members,
            column: :id,
            name: "orders_job_staff_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:orders_job_staff, [:organisation_id, :job_id], name: "orders_job_staff_job_id_index")

    create unique_index(:orders_job_staff, [:organisation_id, :job_id, :member_id],
             name: "orders_job_staff_unique_staff_assignment_index"
           )

    alter table(:orders_job_events) do
      add :actor_id, :uuid
    end

    create table(:orders_job_event_staff, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :man_hour_rate, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_job_event_staff_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_event_id,
          references(:orders_job_events,
            column: :id,
            name: "orders_job_event_staff_job_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :member_id,
          references(:accounts_organisation_members,
            column: :id,
            name: "orders_job_event_staff_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:orders_job_event_staff, [:organisation_id, :job_event_id],
             name: "orders_job_event_staff_job_event_id_index"
           )
  end

  def down do
    drop constraint(:orders_job_event_staff, "orders_job_event_staff_organisation_id_fkey")

    drop constraint(:orders_job_event_staff, "orders_job_event_staff_job_event_id_fkey")

    drop constraint(:orders_job_event_staff, "orders_job_event_staff_member_id_fkey")

    drop_if_exists index(:orders_job_event_staff, [:organisation_id, :job_event_id],
                     name: "orders_job_event_staff_job_event_id_index"
                   )

    drop table(:orders_job_event_staff)

    alter table(:orders_job_events) do
      remove :actor_id
    end

    drop constraint(:orders_job_staff, "orders_job_staff_organisation_id_fkey")

    drop constraint(:orders_job_staff, "orders_job_staff_job_id_fkey")

    drop constraint(:orders_job_staff, "orders_job_staff_member_id_fkey")

    drop_if_exists unique_index(:orders_job_staff, [:organisation_id, :job_id, :member_id],
                     name: "orders_job_staff_unique_staff_assignment_index"
                   )

    drop_if_exists index(:orders_job_staff, [:organisation_id, :job_id], name: "orders_job_staff_job_id_index")

    drop table(:orders_job_staff)

    alter table(:orders_jobs) do
      remove :realized_cost
      remove :duration_estimate
      modify :status, :text, default: "scheduled"
    end
  end
end
