defmodule OpenSauce.Repo.Migrations.RemoveLotTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_movements) do
      remove :lot_id
    end

    drop table(:inventory_lots)

    alter table(:accounts_organisations) do
      add :next_po_number, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :next_po_number
    end

    alter table(:inventory_movements) do
      add :lot_id,
          references(:inventory_lots,
            column: :id,
            name: "inventory_movements_lot_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # Rollback would require recreating the table manually
  end
end
