defmodule OpenSauce.Repo.Migrations.AddScopeTitleToEngagement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_engagements) do
      add :scope_title, :text
    end
  end

  def down do
    alter table(:crm_engagements) do
      remove :scope_title
    end
  end
end
