defmodule OpenSauce.Repo.Migrations.EngagementImageContentHash do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_engagement_images) do
      add :content_hash, :text
    end
  end

  def down do
    alter table(:crm_engagement_images) do
      remove :content_hash
    end
  end
end
