defmodule OpenSauce.Repo.Migrations.AddHeadOfficeVenue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :head_office_venue_id,
          references(:operations_venues,
            column: :id,
            name: "accounts_organisations_head_office_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:accounts_organisations, "accounts_organisations_head_office_venue_id_fkey")

    alter table(:accounts_organisations) do
      remove :head_office_venue_id
    end
  end
end
