defmodule OpenSauce.Repo.Migrations.RemoveEmailSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      remove :smtp_tls
      remove :smtp_password
      remove :smtp_username
      remove :smtp_port
      remove :smtp_host
      remove :email_api_region
      remove :email_api_domain
      remove :email_api_secret
      remove :email_api_key
      remove :email_provider
      remove :email_from_address
      remove :email_from_name
    end
  end

  def down do
    alter table(:settings) do
      add :email_from_name, :text, null: false, default: "OpenSauce"
      add :email_from_address, :text, null: false, default: "noreply@craftplan.app"
      add :email_provider, :text, null: false, default: "smtp"
      add :email_api_key, :binary
      add :email_api_secret, :binary
      add :email_api_domain, :text
      add :email_api_region, :text, default: "us-east-1"
      add :smtp_host, :text
      add :smtp_port, :bigint, default: 587
      add :smtp_username, :text
      add :smtp_password, :text
      add :smtp_tls, :text, default: "if_available"
    end
  end
end
