defmodule OpenSauce.Repo.Migrations.JobInvoiced do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_jobs) do
      add :invoiced, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:orders_jobs) do
      remove :invoiced
    end
  end
end
