defmodule OpenSauce.Repo.Migrations.AddMemberDisplayTitle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisation_members) do
      add :display_title, :text
    end
  end

  def down do
    alter table(:accounts_organisation_members) do
      remove :display_title
    end
  end
end
