defmodule OpenSauce.Repo.Migrations.DropPaintingAddEngagementImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_engagements) do
      remove :painting
    end
  end

  def down do
    alter table(:crm_engagements) do
      add :painting, :text
    end
  end
end
