defmodule OpenSauce.Repo.Migrations.RemoveVenueTypeTimezone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:operations_venues) do
      remove :type
      remove :timezone
    end
  end

  def down do
    alter table(:operations_venues) do
      add :timezone, :text, null: false, default: "UTC"
      add :type, :text, null: false, default: "kitchen"
    end
  end
end
