defmodule OpenSauce.Repo.Migrations.SupplierCatalogues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inventory_supplier_catalogue_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sku, :text
      add :name, :text, null: false
      add :latin_name, :text
      add :cultivar, :text
      add :category, :text, null: false
      add :format, :text
      add :size_cm, :decimal
      add :volume, :decimal
      add :volume_unit, :text
      add :unit_price, :decimal
      add :currency, :text, default: "CAD"
      add :min_order_qty, :bigint, null: false, default: 1
      add :lead_time_days, :bigint
      add :available, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "inventory_supplier_catalogue_items_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :supplier_catalogue_id, :uuid, null: false
      add :material_id, :uuid
    end

    create index(:inventory_supplier_catalogue_items, [:organisation_id, :supplier_catalogue_id],
             name: "inventory_sci_catalogue_index"
           )

    create index(:inventory_supplier_catalogue_items, [:organisation_id, :cultivar], name: "inventory_sci_cultivar_index")

    create index(:inventory_supplier_catalogue_items, [:organisation_id, :latin_name],
             name: "inventory_sci_latin_name_index"
           )

    create table(:inventory_supplier_catalogues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_supplier_catalogue_items) do
      modify :supplier_catalogue_id,
             references(:inventory_supplier_catalogues,
               column: :id,
               name: "inventory_supplier_catalogue_items_supplier_catalogue_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_supplier_catalogue_items_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_supplier_catalogues) do
      add :name, :text, null: false
      add :season, :text, null: false, default: "year_round"
      add :year, :bigint, null: false
      add :valid_from, :date
      add :valid_until, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "inventory_supplier_catalogues_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :supplier_id,
          references(:inventory_suppliers,
            column: :id,
            name: "inventory_supplier_catalogues_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :inventory_supplier_catalogues,
           "inventory_supplier_catalogues_organisation_id_fkey"
         )

    drop constraint(
           :inventory_supplier_catalogues,
           "inventory_supplier_catalogues_supplier_id_fkey"
         )

    alter table(:inventory_supplier_catalogues) do
      remove :supplier_id
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :valid_until
      remove :valid_from
      remove :year
      remove :season
      remove :name
    end

    drop constraint(
           :inventory_supplier_catalogue_items,
           "inventory_supplier_catalogue_items_supplier_catalogue_id_fkey"
         )

    drop constraint(
           :inventory_supplier_catalogue_items,
           "inventory_supplier_catalogue_items_material_id_fkey"
         )

    alter table(:inventory_supplier_catalogue_items) do
      modify :material_id, :uuid
      modify :supplier_catalogue_id, :uuid
    end

    drop table(:inventory_supplier_catalogues)

    drop constraint(
           :inventory_supplier_catalogue_items,
           "inventory_supplier_catalogue_items_organisation_id_fkey"
         )

    drop_if_exists index(:inventory_supplier_catalogue_items, [:organisation_id, :latin_name],
                     name: "inventory_sci_latin_name_index"
                   )

    drop_if_exists index(:inventory_supplier_catalogue_items, [:organisation_id, :cultivar],
                     name: "inventory_sci_cultivar_index"
                   )

    drop_if_exists index(
                     :inventory_supplier_catalogue_items,
                     [:organisation_id, :supplier_catalogue_id],
                     name: "inventory_sci_catalogue_index"
                   )

    drop table(:inventory_supplier_catalogue_items)
  end
end
