defmodule OpenSauce.Repo.Migrations.AddInvoiceLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_invoices) do
      add :line_items, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:crm_invoices) do
      remove :line_items
    end
  end
end
