defmodule OpenSauce.Repo.Migrations.AddCompanyNameNicknameToCustomer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_customers) do
      add :company_name_nickname, :text
    end
  end

  def down do
    alter table(:crm_customers) do
      remove :company_name_nickname
    end
  end
end
