defmodule OpenSauce.Repo.Migrations.AddDefaultSupplierCatalogItemToMaterials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_materials) do
      add :default_supplier_catalog_item_id,
          references(:inventory_supplier_catalog_items,
            column: :id,
            name: "inventory_materials_default_supplier_catalog_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(
           :inventory_materials,
           "inventory_materials_default_supplier_catalog_item_id_fkey"
         )

    alter table(:inventory_materials) do
      remove :default_supplier_catalog_item_id
    end
  end
end
