defmodule OpenSauce.Repo.Migrations.MoveLaborToMemberAndOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      remove :labor_overhead_percent
      remove :labor_hourly_rate
    end

    alter table(:accounts_organisations) do
      add :labor_overhead_percent, :decimal, null: false, default: "0"
    end

    alter table(:accounts_organisation_members) do
      add :labor_hourly_rate, :decimal, null: false, default: "0"
    end
  end

  def down do
    alter table(:accounts_organisation_members) do
      remove :labor_hourly_rate
    end

    alter table(:accounts_organisations) do
      remove :labor_overhead_percent
    end

    alter table(:settings) do
      add :labor_hourly_rate, :decimal, null: false, default: "0"
      add :labor_overhead_percent, :decimal, null: false, default: "0"
    end
  end
end
