defmodule OpenSauce.Repo.Migrations.MoveTaxRatesToAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:settings_tax_rates, "settings_tax_rates_organisation_id_fkey")

    rename table(:settings_tax_rates), to: table(:accounts_tax_rates)

    alter table(:accounts_tax_rates) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "accounts_tax_rates_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:accounts_tax_rates, "accounts_tax_rates_organisation_id_fkey")

    rename table(:accounts_tax_rates), to: table(:settings_tax_rates)

    alter table(:settings_tax_rates) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "settings_tax_rates_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
