defmodule OpenSauce.Repo.Migrations.AddRegistrationNumberToTaxRates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_tax_rates) do
      add :registration_number, :text
    end
  end

  def down do
    alter table(:accounts_tax_rates) do
      remove :registration_number
    end
  end
end
