defmodule OpenSauce.Repo.Migrations.AddressFlagsAndOrgHasOne do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_customers) do
      remove :billing_address_id
    end

    alter table(:crm_addresses) do
      add :is_billing, :boolean, null: false, default: false
      add :is_garden, :boolean, null: false, default: false
      add :is_indoor, :boolean, null: false, default: false
      add :location, :map

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "crm_addresses_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "crm_addresses_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:crm_addresses, [:customer_id])

    alter table(:accounts_organisations) do
      remove :address_id
    end
  end

  def down do
    alter table(:accounts_organisations) do
      add :address_id,
          references(:crm_addresses,
            column: :id,
            name: "accounts_organisations_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists index(:crm_addresses, [:customer_id])

    drop constraint(:crm_addresses, "crm_addresses_organisation_id_fkey")

    drop constraint(:crm_addresses, "crm_addresses_customer_id_fkey")

    alter table(:crm_addresses) do
      modify :customer_id, :uuid
      remove :organisation_id
      remove :location
      remove :is_indoor
      remove :is_garden
      remove :is_billing
    end

    alter table(:crm_customers) do
      add :billing_address_id,
          references(:crm_addresses,
            column: :id,
            name: "crm_customers_billing_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
