defmodule OpenSauce.Repo.Migrations.AddSchedulingStatusAndDueByToJob do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_jobs) do
      modify :status, :text, default: "scheduling"
      add :due_by, :date
    end
  end

  def down do
    alter table(:orders_jobs) do
      remove :due_by
      modify :status, :text, default: "scheduled"
    end
  end
end
