defmodule OpenSauce.Repo.Migrations.JobEventOdometerInt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_job_events) do
      modify :odometer_km, :bigint
    end
  end

  def down do
    alter table(:orders_job_events) do
      modify :odometer_km, :decimal
    end
  end
end
