defmodule OpenSauce.Repo.Migrations.MoveSettingsToOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      remove :tax_rate
      remove :tax_mode
      remove :currency
    end

    alter table(:accounts_organisations) do
      add :currency, :text, null: false, default: "CAD"
      add :tax_mode, :text, null: false, default: "exclusive"
      add :tax_rate, :decimal, null: false, default: "0"
      add :email_from_name, :text, default: "OpenSauce"
      add :email_from_address, :text
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :email_from_address
      remove :email_from_name
      remove :tax_rate
      remove :tax_mode
      remove :currency
    end

    alter table(:settings) do
      add :currency, :text, null: false, default: "CAD"
      add :tax_mode, :text, null: false, default: "exclusive"
      add :tax_rate, :decimal, null: false, default: "0"
    end
  end
end
