defmodule OpenSauce.Repo.Migrations.RemoveForecastSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      remove :forecast_default_horizon_days
      remove :forecast_default_service_level
      remove :forecast_min_samples
      remove :forecast_planned_weight
      remove :forecast_actual_weight
      remove :forecast_lookback_days
    end
  end

  def down do
    alter table(:settings) do
      add :forecast_lookback_days, :bigint, null: false, default: 42
      add :forecast_actual_weight, :decimal, null: false, default: "0.6"
      add :forecast_planned_weight, :decimal, null: false, default: "0.4"
      add :forecast_min_samples, :bigint, null: false, default: 10
      add :forecast_default_service_level, :decimal, null: false, default: "0.95"
      add :forecast_default_horizon_days, :bigint, null: false, default: 14
    end
  end
end
