defmodule OpenSauce.Repo.Migrations.JobEventUnionData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_job_events) do
      remove :odometer_km
      remove :type
      add :data, :map, null: false
    end
  end

  def down do
    alter table(:orders_job_events) do
      remove :data
      add :type, :text, null: false
      add :odometer_km, :bigint
    end
  end
end
