defmodule OpenSauce.Repo.Migrations.AddSupplierAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_addresses) do
      add :supplier_id,
          references(:inventory_suppliers,
            column: :id,
            name: "crm_addresses_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:crm_addresses, "crm_addresses_supplier_id_fkey")

    alter table(:crm_addresses) do
      remove :supplier_id
    end
  end
end
