defmodule OpenSauce.Repo.Migrations.AddMileageCostPerKm do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :mileage_cost_per_km, :decimal, null: false, default: "0"
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :mileage_cost_per_km
    end
  end
end
