defmodule OpenSauce.Repo.Migrations.Jobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_job_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_job_materials_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_id, :uuid, null: false
      add :material_id, :uuid, null: false
    end

    create table(:orders_job_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :timestamp, :utc_datetime, null: false
      add :odometer_km, :decimal
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_job_events_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_id, :uuid, null: false
    end

    create index(:orders_job_events, [:organisation_id, :job_id, :timestamp],
             name: "orders_job_events_job_timeline_index"
           )

    create table(:orders_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_job_materials) do
      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_job_materials_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "orders_job_materials_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_job_events) do
      modify :job_id,
             references(:orders_jobs,
               column: :id,
               name: "orders_job_events_job_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_jobs) do
      add :service_type, :text, null: false
      add :scheduled_at, :utc_datetime
      add :estimated_duration_minutes, :bigint
      add :status, :text, null: false, default: "scheduled"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_jobs_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :customer_id,
          references(:crm_customers,
            column: :id,
            name: "orders_jobs_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :address_id,
          references(:crm_addresses,
            column: :id,
            name: "orders_jobs_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:orders_jobs, [:organisation_id, :status], name: "orders_jobs_status_index")

    create index(:orders_jobs, [:organisation_id, :scheduled_at], name: "orders_jobs_scheduled_at_index")

    create index(:orders_jobs, [:organisation_id, :customer_id], name: "orders_jobs_customer_id_index")
  end

  def down do
    drop constraint(:orders_jobs, "orders_jobs_organisation_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_customer_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_address_id_fkey")

    drop_if_exists index(:orders_jobs, [:organisation_id, :customer_id], name: "orders_jobs_customer_id_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :scheduled_at], name: "orders_jobs_scheduled_at_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :status], name: "orders_jobs_status_index")

    alter table(:orders_jobs) do
      remove :address_id
      remove :customer_id
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :status
      remove :estimated_duration_minutes
      remove :scheduled_at
      remove :service_type
    end

    drop constraint(:orders_job_events, "orders_job_events_job_id_fkey")

    alter table(:orders_job_events) do
      modify :job_id, :uuid
    end

    drop constraint(:orders_job_materials, "orders_job_materials_job_id_fkey")

    drop constraint(:orders_job_materials, "orders_job_materials_material_id_fkey")

    alter table(:orders_job_materials) do
      modify :material_id, :uuid
      modify :job_id, :uuid
    end

    drop table(:orders_jobs)

    drop constraint(:orders_job_events, "orders_job_events_organisation_id_fkey")

    drop_if_exists index(:orders_job_events, [:organisation_id, :job_id, :timestamp],
                     name: "orders_job_events_job_timeline_index"
                   )

    drop table(:orders_job_events)

    drop constraint(:orders_job_materials, "orders_job_materials_organisation_id_fkey")

    drop table(:orders_job_materials)
  end
end
