defmodule OpenSauce.Repo.Migrations.RedesignJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:operations_shifts)

    drop_if_exists index(:orders_jobs, [:organisation_id, :scheduled_at], name: "orders_jobs_scheduled_at_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :customer_id], name: "orders_jobs_customer_id_index")

    alter table(:orders_jobs) do
      remove :invoice_id
      remove :address_id
      remove :customer_id
      remove :estimated_duration_minutes
      remove :scheduled_at
      remove :service_type
      modify :status, :text, default: "scheduled"
      add :type, :text, null: false, default: "client_work"
      add :service_category, :text
      add :account_code, :text
      add :scheduled_for, :date

      add :garden_id,
          references(:crm_addresses,
            column: :id,
            name: "orders_jobs_garden_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :containing_shift_id,
          references(:orders_jobs,
            column: :id,
            name: "orders_jobs_containing_shift_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :actor_id,
          references(:accounts_users,
            column: :id,
            name: "orders_jobs_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:orders_jobs, [:organisation_id, :garden_id], name: "orders_jobs_garden_id_index")

    create index(:orders_jobs, [:organisation_id, :engagement_id], name: "orders_jobs_engagement_id_index")

    create index(:orders_jobs, [:organisation_id, :containing_shift_id], name: "orders_jobs_containing_shift_id_index")

    create index(:orders_jobs, [:organisation_id, :scheduled_for], name: "orders_jobs_scheduled_for_index")

    execute("UPDATE orders_jobs SET status = 'scheduled' WHERE status = 'planned'")
  end

  def down do
    drop constraint(:orders_jobs, "orders_jobs_garden_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_containing_shift_id_fkey")

    drop constraint(:orders_jobs, "orders_jobs_actor_id_fkey")

    drop_if_exists index(:orders_jobs, [:organisation_id, :scheduled_for], name: "orders_jobs_scheduled_for_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :containing_shift_id],
                     name: "orders_jobs_containing_shift_id_index"
                   )

    drop_if_exists index(:orders_jobs, [:organisation_id, :engagement_id], name: "orders_jobs_engagement_id_index")

    drop_if_exists index(:orders_jobs, [:organisation_id, :garden_id], name: "orders_jobs_garden_id_index")

    alter table(:orders_jobs) do
      remove :actor_id
      remove :containing_shift_id
      remove :garden_id
      remove :scheduled_for
      remove :account_code
      remove :service_category
      remove :type
      modify :status, :text, default: "scheduled"
      add :service_type, :text, null: false
      add :scheduled_at, :utc_datetime
      add :estimated_duration_minutes, :bigint

      add :customer_id,
          references(:crm_customers,
            column: :id,
            name: "orders_jobs_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :address_id,
          references(:crm_addresses,
            column: :id,
            name: "orders_jobs_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :invoice_id,
          references(:crm_invoices,
            column: :id,
            name: "orders_jobs_invoice_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:orders_jobs, [:organisation_id, :customer_id], name: "orders_jobs_customer_id_index")

    create index(:orders_jobs, [:organisation_id, :scheduled_at], name: "orders_jobs_scheduled_at_index")
  end
end
