defmodule OpenSauce.Repo.Migrations.LotVenued do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_lots) do
      add :venue_id,
          references(:operations_venues,
            column: :id,
            name: "inventory_lots_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:inventory_lots, "inventory_lots_venue_id_fkey")

    alter table(:inventory_lots) do
      remove :venue_id
    end
  end
end
