defmodule OpenSauce.Repo.Migrations.DropFormatAddFormatDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:inventory_supplier_catalogue_items, [:organisation_id, :cultivar],
                     name: "inventory_sci_cultivar_index"
                   )

    drop_if_exists index(:inventory_supplier_catalogue_items, [:organisation_id, :latin_name],
                     name: "inventory_sci_latin_name_index"
                   )

    alter table(:inventory_supplier_catalogue_items) do
      remove :volume_unit
      remove :volume
      remove :format
      add :format_description, :text
    end
  end

  def down do
    alter table(:inventory_supplier_catalogue_items) do
      remove :format_description
      add :format, :text
      add :volume, :decimal
      add :volume_unit, :text
    end

    create index(:inventory_supplier_catalogue_items, [:organisation_id, :latin_name],
             name: "inventory_sci_latin_name_index"
           )

    create index(:inventory_supplier_catalogue_items, [:organisation_id, :cultivar], name: "inventory_sci_cultivar_index")
  end
end
