defmodule OpenSauce.Repo.Migrations.DropProduction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_items) do
      remove :production_batch_id
      remove :unit_cost
      remove :overhead_cost
      remove :labor_cost
      remove :material_cost
      remove :batch_code
      remove :consumed_at
    end
  end

  def down do
    alter table(:orders_items) do
      add :consumed_at, :utc_datetime
      add :batch_code, :text
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_items_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
