defmodule OpenSauce.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false, default: "CAD"
      add :tax_mode, :text, null: false, default: "exclusive"
      add :tax_rate, :decimal, null: false, default: "0"
      add :offers_pickup, :boolean, null: false, default: true
      add :offers_delivery, :boolean, null: false, default: true
      add :lead_time_days, :bigint, null: false, default: 0
      add :daily_capacity, :bigint, null: false, default: 0
      add :shipping_flat, :decimal, null: false, default: "0"
      add :labor_hourly_rate, :decimal, null: false, default: "0"
      add :labor_overhead_percent, :decimal, null: false, default: "0"
      add :retail_markup_mode, :text, null: false, default: "percent"
      add :retail_markup_value, :decimal, null: false, default: "0"
      add :wholesale_markup_mode, :text, null: false, default: "percent"
      add :wholesale_markup_value, :decimal, null: false, default: "0"
      add :email_from_name, :text, null: false, default: "OpenSauce"
      add :email_from_address, :text, null: false, default: "noreply@craftplan.app"
      add :email_provider, :text, null: false, default: "smtp"
      add :email_api_key, :binary
      add :email_api_secret, :binary
      add :email_api_domain, :text
      add :email_api_region, :text, default: "us-east-1"
      add :smtp_host, :text
      add :smtp_port, :bigint, default: 587
      add :smtp_username, :text
      add :smtp_password, :text
      add :smtp_tls, :text, default: "if_available"
      add :forecast_lookback_days, :bigint, null: false, default: 42
      add :forecast_actual_weight, :decimal, null: false, default: "0.6"
      add :forecast_planned_weight, :decimal, null: false, default: "0.4"
      add :forecast_min_samples, :bigint, null: false, default: 10
      add :forecast_default_service_level, :decimal, null: false, default: "0.95"
      add :forecast_default_horizon_days, :bigint, null: false, default: 14
      add :organisation_id, :uuid, null: false
    end

    create table(:orders_production_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :batch_code, :text, null: false
      add :planned_qty, :decimal, null: false, default: "0"
      add :produced_qty, :decimal, null: false, default: "0"
      add :scrap_qty, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "open"
      add :notes, :text
      add :bom_version, :bigint
      add :components_map, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :product_id, :uuid, null: false
      add :bom_id, :uuid
    end

    create index(:orders_production_batches, [:organisation_id, :batch_code],
             name: "orders_production_batches_batch_code_index",
             unique: true
           )

    create table(:orders_production_batch_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_production_batch_lots_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :lot_id, :uuid, null: false
    end

    create index(:orders_production_batch_lots, [:lot_id], name: "orders_production_batch_lots_lot_idx")

    create index(:orders_production_batch_lots, [:production_batch_id], name: "orders_production_batch_lots_batch_idx")

    create table(:orders_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false, default: "CAD"
      add :reference, :text, null: false
      add :delivery_date, :utc_datetime, null: false
      add :invoice_number, :text
      add :invoice_status, :text, null: false, default: "none"
      add :invoiced_at, :utc_datetime
      add :payment_method, :text
      add :discount_type, :text, null: false, default: "none"
      add :discount_value, :decimal, null: false, default: "0"
      add :delivery_method, :text, null: false, default: "delivery"
      add :status, :text, null: false, default: "unconfirmed"
      add :payment_status, :text, null: false, default: "pending"
      add :subtotal, :decimal, null: false, default: "0"
      add :tax_total, :decimal, null: false, default: "0"
      add :shipping_total, :decimal, null: false, default: "0"
      add :discount_total, :decimal, null: false, default: "0"
      add :total, :decimal, null: false, default: "0"
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :customer_id, :uuid, null: false
    end

    create unique_index(:orders_orders, [:organisation_id, :reference], name: "orders_orders_reference_index")

    create table(:orders_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :unit_price, :decimal, null: false
      add :quantity, :decimal, null: false
      add :status, :text, null: false, default: "todo"
      add :consumed_at, :utc_datetime
      add :batch_code, :text
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :order_id, :uuid, null: false
      add :product_id, :uuid, null: false
      add :bom_id, :uuid
      add :production_batch_id, :uuid
    end

    create table(:orders_item_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_lots_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :lot_id, :uuid, null: false
    end

    create table(:orders_item_batch_allocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :planned_qty, :decimal, null: false, default: "0"
      add :completed_qty, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_item_batch_allocations_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_batch_allocations_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:orders_item_batch_allocations, [:production_batch_id], name: "orders_item_batch_allocations_batch_idx")

    create index(:orders_item_batch_allocations, [:order_item_id], name: "orders_item_batch_allocations_item_idx")

    create index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
             name: "orders_item_batch_allocations_unique_pair",
             unique: true
           )

    create table(:operations_venues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create table(:operations_storage_locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :venue_id, :uuid, null: false
    end

    create table(:operations_shifts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :venue_id, :uuid, null: false
      add :member_id, :uuid, null: false
    end

    create table(:inventory_suppliers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :contact_name, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create table(:inventory_purchase_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :ordered_at, :utc_datetime
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :supplier_id, :uuid, null: false
    end

    create unique_index(:inventory_purchase_orders, [:organisation_id, :reference],
             name: "inventory_purchase_orders_reference_index"
           )

    create table(:inventory_purchase_order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false, default: "0"
      add :unit_price, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :purchase_order_id,
          references(:inventory_purchase_orders,
            column: :id,
            name: "inventory_purchase_order_items_purchase_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :material_id, :uuid, null: false
    end

    create table(:inventory_nutritional_facts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_nutritional_facts, [:name], name: "inventory_nutritional_facts_name_index")

    create table(:inventory_movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :reason, :text
      add :occurred_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :lot_id, :uuid
    end

    create table(:inventory_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_purchase_order_items) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_purchase_order_items_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_materials) do
      add :name, :text, null: false
      add :sku, :text, null: false
      add :unit, :text, null: false
      add :price, :decimal, null: false
      add :minimum_stock, :decimal
      add :maximum_stock, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create unique_index(:inventory_materials, [:organisation_id, :name], name: "inventory_materials_name_index")

    create unique_index(:inventory_materials, [:organisation_id, :sku], name: "inventory_materials_sku_index")

    create table(:inventory_material_nutritional_fact, primary_key: false) do
      add :amount, :decimal, null: false
      add :unit, :text, null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_nutritional_fact_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :nutritional_fact_id,
          references(:inventory_nutritional_facts,
            column: :id,
            name: "inventory_material_nutritional_fact_nutritional_fact_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create table(:inventory_material_allergen, primary_key: false) do
      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_allergen_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :allergen_id, :uuid, null: false, primary_key: true
    end

    create table(:inventory_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_production_batch_lots) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_production_batch_lots_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_item_lots) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_item_lots_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_lots) do
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :supplier_id, :uuid
    end

    create index(:inventory_lots, [:organisation_id, :supplier_id], name: "inventory_lots_supplier_id_index")

    create index(:inventory_lots, [:organisation_id, :material_id], name: "inventory_lots_material_id_index")

    create index(:inventory_lots, [:organisation_id, :lot_code],
             name: "inventory_lots_lot_code_index",
             unique: true
           )

    create table(:inventory_allergens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_material_allergen) do
      modify :allergen_id,
             references(:inventory_allergens,
               column: :id,
               name: "inventory_material_allergen_allergen_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_allergens) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_allergens, [:name], name: "inventory_allergens_name_index")

    create table(:crm_customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :type, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :text
      add :phone, :text
      add :billing_address, :map
      add :shipping_address, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create unique_index(:crm_customers, [:organisation_id, :email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:organisation_id, :phone], name: "crm_customers_phone_index")

    create unique_index(:crm_customers, [:organisation_id, :reference], name: "crm_customers_reference_index")

    create table(:catalog_products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :price, :decimal, null: false
      add :sku, :text, null: false
      add :photos, {:array, :text}, default: []
      add :featured_photo, :text
      add :selling_availability, :text, null: false, default: "available"
      add :max_daily_quantity, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
    end

    create unique_index(:catalog_products, [:organisation_id, :name], name: "catalog_products_name_index")

    create unique_index(:catalog_products, [:organisation_id, :sku], name: "catalog_products_sku_index")

    create table(:catalog_labor_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sequence, :bigint, null: false, default: 0
      add :duration_minutes, :decimal, null: false, default: "0"
      add :rate_override, :decimal
      add :units_per_run, :decimal, null: false, default: "1"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id, :uuid, null: false
    end

    create table(:catalog_boms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:catalog_labor_steps) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_labor_steps_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalog_boms) do
      add :name, :text
      add :notes, :text
      add :status, :text, null: false, default: "draft"
      add :version, :bigint, null: false
      add :published_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id, :uuid, null: false
      add :product_id, :uuid, null: false
    end

    create index(:catalog_boms, [:organisation_id, :product_id],
             name: "catalog_boms_one_active_per_product",
             unique: true,
             where: "status = 'active'"
           )

    create unique_index(:catalog_boms, [:organisation_id, :product_id, :version],
             name: "catalog_boms_product_version_index"
           )

    create table(:catalog_bom_rollups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"
      add :components_map, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id,
          references(:catalog_boms,
            column: :id,
            name: "catalog_bom_rollups_bom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "catalog_bom_rollups_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:catalog_bom_rollups, [:bom_id], name: "catalog_bom_rollups_unique_bom_index")

    create table(:catalog_bom_components, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :component_type, :text, null: false, default: "material"
      add :quantity, :decimal, null: false, default: "0"
      add :position, :bigint, null: false, default: 0
      add :waste_percent, :decimal, null: false, default: "0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id,
          references(:catalog_boms,
            column: :id,
            name: "catalog_bom_components_bom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "catalog_bom_components_material_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "catalog_bom_components_product_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:accounts_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    create table(:accounts_tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:accounts_organisations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:settings) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "settings_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_production_batches) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_production_batches_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "orders_production_batches_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "orders_production_batches_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_orders) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_orders_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "orders_orders_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders_items) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "orders_items_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :order_id,
             references(:orders_orders,
               column: :id,
               name: "orders_items_order_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "orders_items_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "orders_items_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :production_batch_id,
             references(:orders_production_batches,
               column: :id,
               name: "orders_items_production_batch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations_venues) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "operations_venues_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations_storage_locations) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "operations_storage_locations_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:operations_venues,
               column: :id,
               name: "operations_storage_locations_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations_shifts) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "operations_shifts_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:operations_venues,
               column: :id,
               name: "operations_shifts_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_suppliers) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_suppliers_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_purchase_orders) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_purchase_orders_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_purchase_orders_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_movements) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_movements_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_movements_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "inventory_movements_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_materials) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_materials_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_lots) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "inventory_lots_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_lots_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_lots_supplier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_customers) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "crm_customers_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalog_products) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "catalog_products_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalog_boms) do
      modify :organisation_id,
             references(:accounts_organisations,
               column: :id,
               name: "catalog_boms_organisation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "catalog_boms_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_organisations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts_organisations, [:slug], name: "accounts_organisations_unique_slug_index")

    create table(:accounts_organisation_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:operations_shifts) do
      modify :member_id,
             references(:accounts_organisation_members,
               column: :id,
               name: "operations_shifts_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_organisation_members) do
      add :role, :text, null: false, default: "staff"
      add :display_title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_organisation_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "accounts_organisation_members_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_organisation_members, [:user_id, :organisation_id],
             name: "accounts_organisation_members_unique_membership_index"
           )

    create table(:accounts_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, :map, null: false, default: %{}
      add :last_used_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "accounts_api_keys_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_api_keys, [:organisation_id, :key_hash], name: "accounts_api_keys_key_hash_index")
  end

  def down do
    drop constraint(:accounts_api_keys, "accounts_api_keys_organisation_id_fkey")

    drop_if_exists unique_index(:accounts_api_keys, [:organisation_id, :key_hash],
                     name: "accounts_api_keys_key_hash_index"
                   )

    drop table(:accounts_api_keys)

    drop constraint(:accounts_organisation_members, "accounts_organisation_members_user_id_fkey")

    drop constraint(
           :accounts_organisation_members,
           "accounts_organisation_members_organisation_id_fkey"
         )

    drop_if_exists unique_index(:accounts_organisation_members, [:user_id, :organisation_id],
                     name: "accounts_organisation_members_unique_membership_index"
                   )

    alter table(:accounts_organisation_members) do
      remove :organisation_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :display_title
      remove :role
    end

    drop constraint(:operations_shifts, "operations_shifts_member_id_fkey")

    alter table(:operations_shifts) do
      modify :member_id, :uuid
    end

    drop table(:accounts_organisation_members)

    drop_if_exists unique_index(:accounts_organisations, [:slug], name: "accounts_organisations_unique_slug_index")

    alter table(:accounts_organisations) do
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:catalog_boms, "catalog_boms_organisation_id_fkey")

    drop constraint(:catalog_boms, "catalog_boms_product_id_fkey")

    alter table(:catalog_boms) do
      modify :product_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:catalog_products, "catalog_products_organisation_id_fkey")

    alter table(:catalog_products) do
      modify :organisation_id, :uuid
    end

    drop constraint(:crm_customers, "crm_customers_organisation_id_fkey")

    alter table(:crm_customers) do
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_lots, "inventory_lots_organisation_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_material_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_supplier_id_fkey")

    alter table(:inventory_lots) do
      modify :supplier_id, :uuid
      modify :material_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_materials, "inventory_materials_organisation_id_fkey")

    alter table(:inventory_materials) do
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_movements, "inventory_movements_organisation_id_fkey")

    drop constraint(:inventory_movements, "inventory_movements_material_id_fkey")

    drop constraint(:inventory_movements, "inventory_movements_lot_id_fkey")

    alter table(:inventory_movements) do
      modify :lot_id, :uuid
      modify :material_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_organisation_id_fkey")

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_supplier_id_fkey")

    alter table(:inventory_purchase_orders) do
      modify :supplier_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:inventory_suppliers, "inventory_suppliers_organisation_id_fkey")

    alter table(:inventory_suppliers) do
      modify :organisation_id, :uuid
    end

    drop constraint(:operations_shifts, "operations_shifts_organisation_id_fkey")

    drop constraint(:operations_shifts, "operations_shifts_venue_id_fkey")

    alter table(:operations_shifts) do
      modify :venue_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(
           :operations_storage_locations,
           "operations_storage_locations_organisation_id_fkey"
         )

    drop constraint(:operations_storage_locations, "operations_storage_locations_venue_id_fkey")

    alter table(:operations_storage_locations) do
      modify :venue_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:operations_venues, "operations_venues_organisation_id_fkey")

    alter table(:operations_venues) do
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_items, "orders_items_organisation_id_fkey")

    drop constraint(:orders_items, "orders_items_order_id_fkey")

    drop constraint(:orders_items, "orders_items_product_id_fkey")

    drop constraint(:orders_items, "orders_items_bom_id_fkey")

    drop constraint(:orders_items, "orders_items_production_batch_id_fkey")

    alter table(:orders_items) do
      modify :production_batch_id, :uuid
      modify :bom_id, :uuid
      modify :product_id, :uuid
      modify :order_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_orders, "orders_orders_organisation_id_fkey")

    drop constraint(:orders_orders, "orders_orders_customer_id_fkey")

    alter table(:orders_orders) do
      modify :customer_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:orders_production_batches, "orders_production_batches_organisation_id_fkey")

    drop constraint(:orders_production_batches, "orders_production_batches_product_id_fkey")

    drop constraint(:orders_production_batches, "orders_production_batches_bom_id_fkey")

    alter table(:orders_production_batches) do
      modify :bom_id, :uuid
      modify :product_id, :uuid
      modify :organisation_id, :uuid
    end

    drop constraint(:settings, "settings_organisation_id_fkey")

    alter table(:settings) do
      modify :organisation_id, :uuid
    end

    drop table(:accounts_organisations)

    drop table(:accounts_tokens)

    drop_if_exists unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    drop table(:accounts_users)

    drop constraint(:catalog_bom_components, "catalog_bom_components_bom_id_fkey")

    drop constraint(:catalog_bom_components, "catalog_bom_components_material_id_fkey")

    drop constraint(:catalog_bom_components, "catalog_bom_components_product_id_fkey")

    drop table(:catalog_bom_components)

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_bom_id_fkey")

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_product_id_fkey")

    drop_if_exists unique_index(:catalog_bom_rollups, [:bom_id], name: "catalog_bom_rollups_unique_bom_index")

    drop table(:catalog_bom_rollups)

    drop_if_exists unique_index(:catalog_boms, [:organisation_id, :product_id, :version],
                     name: "catalog_boms_product_version_index"
                   )

    drop_if_exists index(:catalog_boms, [:organisation_id, :product_id], name: "catalog_boms_one_active_per_product")

    alter table(:catalog_boms) do
      remove :product_id
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :version
      remove :status
      remove :notes
      remove :name
    end

    drop constraint(:catalog_labor_steps, "catalog_labor_steps_bom_id_fkey")

    alter table(:catalog_labor_steps) do
      modify :bom_id, :uuid
    end

    drop table(:catalog_boms)

    drop table(:catalog_labor_steps)

    drop_if_exists unique_index(:catalog_products, [:organisation_id, :sku], name: "catalog_products_sku_index")

    drop_if_exists unique_index(:catalog_products, [:organisation_id, :name], name: "catalog_products_name_index")

    drop table(:catalog_products)

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :reference], name: "crm_customers_reference_index")

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :phone], name: "crm_customers_phone_index")

    drop_if_exists unique_index(:crm_customers, [:organisation_id, :email], name: "crm_customers_email_index")

    drop table(:crm_customers)

    drop_if_exists unique_index(:inventory_allergens, [:name], name: "inventory_allergens_name_index")

    alter table(:inventory_allergens) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_allergen_id_fkey")

    alter table(:inventory_material_allergen) do
      modify :allergen_id, :uuid
    end

    drop table(:inventory_allergens)

    drop_if_exists index(:inventory_lots, [:organisation_id, :lot_code], name: "inventory_lots_lot_code_index")

    drop_if_exists index(:inventory_lots, [:organisation_id, :material_id], name: "inventory_lots_material_id_index")

    drop_if_exists index(:inventory_lots, [:organisation_id, :supplier_id], name: "inventory_lots_supplier_id_index")

    alter table(:inventory_lots) do
      remove :supplier_id
      remove :material_id
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :received_at
      remove :expiry_date
      remove :lot_code
    end

    drop constraint(:orders_item_lots, "orders_item_lots_lot_id_fkey")

    alter table(:orders_item_lots) do
      modify :lot_id, :uuid
    end

    drop constraint(:orders_production_batch_lots, "orders_production_batch_lots_lot_id_fkey")

    alter table(:orders_production_batch_lots) do
      modify :lot_id, :uuid
    end

    drop table(:inventory_lots)

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_material_id_fkey")

    drop table(:inventory_material_allergen)

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_material_id_fkey"
         )

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_nutritional_fact_id_fkey"
         )

    drop table(:inventory_material_nutritional_fact)

    drop_if_exists unique_index(:inventory_materials, [:organisation_id, :sku], name: "inventory_materials_sku_index")

    drop_if_exists unique_index(:inventory_materials, [:organisation_id, :name], name: "inventory_materials_name_index")

    alter table(:inventory_materials) do
      remove :organisation_id
      remove :updated_at
      remove :inserted_at
      remove :maximum_stock
      remove :minimum_stock
      remove :price
      remove :unit
      remove :sku
      remove :name
    end

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_material_id_fkey"
         )

    alter table(:inventory_purchase_order_items) do
      modify :material_id, :uuid
    end

    drop table(:inventory_materials)

    drop table(:inventory_movements)

    drop_if_exists unique_index(:inventory_nutritional_facts, [:name], name: "inventory_nutritional_facts_name_index")

    drop table(:inventory_nutritional_facts)

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_purchase_order_id_fkey"
         )

    drop table(:inventory_purchase_order_items)

    drop_if_exists unique_index(:inventory_purchase_orders, [:organisation_id, :reference],
                     name: "inventory_purchase_orders_reference_index"
                   )

    drop table(:inventory_purchase_orders)

    drop table(:inventory_suppliers)

    drop table(:operations_shifts)

    drop table(:operations_storage_locations)

    drop table(:operations_venues)

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_production_batch_id_fkey"
         )

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
                     name: "orders_item_batch_allocations_unique_pair"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:order_item_id], name: "orders_item_batch_allocations_item_idx")

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id],
                     name: "orders_item_batch_allocations_batch_idx"
                   )

    drop table(:orders_item_batch_allocations)

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    drop table(:orders_item_lots)

    drop table(:orders_items)

    drop_if_exists unique_index(:orders_orders, [:organisation_id, :reference], name: "orders_orders_reference_index")

    drop table(:orders_orders)

    drop constraint(
           :orders_production_batch_lots,
           "orders_production_batch_lots_production_batch_id_fkey"
         )

    drop_if_exists index(:orders_production_batch_lots, [:production_batch_id],
                     name: "orders_production_batch_lots_batch_idx"
                   )

    drop_if_exists index(:orders_production_batch_lots, [:lot_id], name: "orders_production_batch_lots_lot_idx")

    drop table(:orders_production_batch_lots)

    drop_if_exists index(:orders_production_batches, [:organisation_id, :batch_code],
                     name: "orders_production_batches_batch_code_index"
                   )

    drop table(:orders_production_batches)

    drop table(:settings)
  end
end
