defmodule OpenSauce.Repo.Migrations.AddAddressResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_customers) do
      remove :shipping_address
      remove :billing_address
      add :billing_address_id, :uuid
    end

    create table(:crm_addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:crm_customers) do
      modify :billing_address_id,
             references(:crm_addresses,
               column: :id,
               name: "crm_customers_billing_address_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crm_addresses) do
      add :name, :text
      add :street, :text
      add :city, :text
      add :province, :text
      add :zip, :text
      add :country, :text
      add :customer_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:accounts_organisations) do
      add :address_id,
          references(:crm_addresses,
            column: :id,
            name: "accounts_organisations_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:accounts_organisations, "accounts_organisations_address_id_fkey")

    alter table(:accounts_organisations) do
      remove :address_id
    end

    alter table(:crm_addresses) do
      remove :updated_at
      remove :inserted_at
      remove :customer_id
      remove :country
      remove :zip
      remove :province
      remove :city
      remove :street
      remove :name
    end

    drop constraint(:crm_customers, "crm_customers_billing_address_id_fkey")

    alter table(:crm_customers) do
      modify :billing_address_id, :uuid
    end

    drop table(:crm_addresses)

    alter table(:crm_customers) do
      remove :billing_address_id
      add :billing_address, :map
      add :shipping_address, :map
    end
  end
end
