defmodule OpenSauce.Repo.Migrations.PoItemCherryPick do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_supplier_catalogue_items) do
      modify :sku, :text, null: false
    end

    alter table(:inventory_purchase_order_items) do
      modify :material_id, :uuid, null: true
      modify :quantity, :decimal, default: "1"
      add :supplier_sku, :text, null: false
      add :confirmed_qty, :decimal
      add :received_qty, :decimal
      add :is_reservation, :boolean, null: false, default: false

      add :supplier_catalogue_item_id,
          references(:inventory_supplier_catalogue_items,
            column: :id,
            name: "inventory_purchase_order_items_supplier_catalogue_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_supplier_catalogue_item_id_fkey"
         )

    alter table(:inventory_purchase_order_items) do
      remove :supplier_catalogue_item_id
      remove :is_reservation
      remove :received_qty
      remove :confirmed_qty
      remove :supplier_sku
      modify :quantity, :decimal, default: "0"
      modify :material_id, :uuid, null: false
    end

    alter table(:inventory_supplier_catalogue_items) do
      modify :sku, :text, null: true
    end
  end
end
