defmodule OpenSauce.Repo.Migrations.AddJobEventMaterials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_job_event_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organisation_id,
          references(:accounts_organisations,
            column: :id,
            name: "orders_job_event_materials_organisation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_event_id,
          references(:orders_job_events,
            column: :id,
            name: "orders_job_event_materials_job_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "orders_job_event_materials_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :orders_job_event_materials,
           "orders_job_event_materials_organisation_id_fkey"
         )

    drop constraint(:orders_job_event_materials, "orders_job_event_materials_job_event_id_fkey")

    drop constraint(:orders_job_event_materials, "orders_job_event_materials_material_id_fkey")

    drop table(:orders_job_event_materials)
  end
end
