defmodule OpenSauce.Repo.Migrations.AddOrgIdentityAndContactFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts_organisations) do
      add :legal_name, :text
      add :website, :text
      add :phone, :text
      add :payment_info, :text
      add :invoice_terms, :text
      add :invoice_footer, :text
      add :contact_name, :text
      add :contact_title, :text
      add :contact_phone, :text
      add :contact_email, :text
    end
  end

  def down do
    alter table(:accounts_organisations) do
      remove :contact_email
      remove :contact_phone
      remove :contact_title
      remove :contact_name
      remove :invoice_footer
      remove :invoice_terms
      remove :payment_info
      remove :phone
      remove :website
      remove :legal_name
    end
  end
end
